name: VERSA CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8
        pip install -e .
    - name: Check formatting with Black
      run: |
        black --check versa scripts test *.py
    - name: Lint with flake8
      run: |
        flake8 versa scripts test *.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 versa scripts test *.py --count --exit-zero --max-line-length=127 --statistics

  install-tests:
    needs: code-quality
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        python-version: ['3.8', '3.9', '3.10']
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
    - name: Test installation
      run: |
        python -c "import versa; print(versa.__version__)"

  basic-tests:
    needs: install-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
    - name: Run basic tests
      run: |
        pytest -xvs test/test_general.py

  metric-tests:
    needs: basic-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
    - name: Run metric tests
      run: |
        pytest -xvs test/test_metrics/test_stoi.py
        # Additional metric tests can be added here as they're developed
        # pytest -xvs test/test_metrics/test_pesq.py
        # pytest -xvs test/test_metrics/test_sisdr.py
        # etc.
